import Image from "next/image";
import type { Tool } from "@/lib/types";
import { getDomain } from "@/lib/utils";
import { RatingBadge } from "@/components/RatingBadge";
import { UpdateBadge } from "@/components/UpdateBadge";

export function ToolDetailHeader({ tool }: { tool: Tool }) {
  return <header className="rounded-[2rem] border border-white/10 bg-gradient-to-br from-white/[0.08] to-white/[0.02] p-6 sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-center"><div className="relative grid size-24 shrink-0 place-items-center overflow-hidden rounded-3xl bg-gradient-to-br from-cyan-300 to-violet-500 text-3xl font-black text-zinc-950">{tool.logo_url ? <Image src={tool.logo_url} alt={`${tool.tool_name} logo`} fill className="object-cover" /> : tool.tool_name.slice(0, 2)}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2 text-xs font-semibold text-cyan-200"><span>{tool.category}</span><span>/</span><span>{tool.sub_category}</span></div><h1 className="mt-2 text-4xl font-black">{tool.tool_name}</h1><p className="mt-3 max-w-3xl text-zinc-400">{tool.short_description}</p><div className="mt-4 flex flex-wrap items-center gap-2"><RatingBadge rating={tool.rating_average} count={tool.rating_count} /><span className="rounded-full bg-white/5 px-2.5 py-1 text-xs text-zinc-300">댓글 {tool.comment_count}</span><UpdateBadge date={tool.last_update_date} /><span className="rounded-full bg-white/5 px-2.5 py-1 text-xs text-zinc-300">{tool.pricing}</span><span className="rounded-full bg-white/5 px-2.5 py-1 text-xs text-zinc-300">{tool.difficulty}</span><span className="rounded-full bg-white/5 px-2.5 py-1 text-xs text-zinc-300">한국어 {tool.korean_support ? "지원" : "확인 필요"}</span></div></div><div className="flex flex-col gap-3 sm:flex-row lg:flex-col"><a href={tool.official_url} target="_blank" rel="noreferrer" className="rounded-2xl bg-cyan-300 px-5 py-3 text-center text-sm font-black text-zinc-950 hover:bg-cyan-200">공식 사이트 바로가기</a><button className="rounded-2xl border border-white/10 px-5 py-3 text-sm font-bold text-zinc-200 hover:bg-white/5">즐겨찾기 ☆</button><span className="text-center text-xs text-zinc-500">{getDomain(tool.official_url)}</span></div></div></header>;
}
